export const ALL_TRADE_REQUEST = "ALL_TRADE_REQUEST";
export const ALL_TRADE_SUCCESS = "ALL_TRADE_SUCCESS";
export const ALL_TRADE_FAIL = "ALL_TRADE_FAIL";

export const TRADE_DETAILS_REQUEST = "TRADE_DETAILS_REQUEST";
export const TRADE_DETAILS_SUCCESS = "TRADE_DETAILS_SUCCESS";
export const TRADE_DETAILS_FAIL = "TRADE_DETAILS_FAIL";

export const ADMIN_TRADE_REQUEST = "ADMIN_TRADE_REQUEST";
export const ADMIN_TRADE_SUCCESS = "ADMIN_TRADE_SUCCESS";
export const ADMIN_TRADE_FAIL = "ADMIN_TRADE_FAIL";

export const NEW_TRADE_REQUEST = "NEW_TRADE_REQUEST";
export const NEW_TRADE_SUCCESS = "NEW_TRADE_SUCCESS";
export const NEW_TRADE_RESET = "NEW_TRADE_RESET";
export const NEW_TRADE_FAIL = "NEW_TRADE_FAIL";

export const UPDATE_TRADE_REQUEST = "UPDATE_TRADE_REQUEST";
export const UPDATE_TRADE_SUCCESS = "UPDATE_TRADE_SUCCESS";
export const UPDATE_TRADE_RESET = "UPDATE_TRADE_RESET";
export const UPDATE_TRADE_FAIL = "UPDATE_TRADE_FAIL";

export const DELETE_TRADE_REQUEST = "DELETE_TRADE_REQUEST";
export const DELETE_TRADE_SUCCESS = "DELETE_TRADE_SUCCESS";
export const DELETE_TRADE_RESET = "DELETE_TRADE_RESET";
export const DELETE_TRADE_FAIL = "DELETE_TRADE_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";


export const CLEAR_ERRORS = 'CLEAR_ERRORS';